path: \Users\dingy\Desktop\Utar_Degree\Year_4_Sem_1\MSD2\MSD_Programs\data\Smart Dustbin v1  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

nc: 3

# Classes
names:
  0: Battery
  1: E_Devices
  2: Alu_Can